### ISSUE TITLE
Without "get_losses.m"

### ISSUE THREAD

**Issue by guduxingzhe11** [zhanjunpeng/SOE#1]
Without "get_losses.m"

**Comment by zhanjunpeng** [comment]
get_losses() is a function of MatPower as explained in this link: https://matpower.org/docs/ref/matpower5.0/get_losses.html

Before running the code, the path to the MatPower toolbox needs to be added. The MatPower can be downloaded from github.com/MATPOWER/matpower

**Comment by guduxingzhe11** [comment]
OK, thank you, senior fellow apprentice!













--

张银
广西科技大学 电气与信息工程学院 ，讲师
中国  广西 柳州 
545006
 
Zhang, Y.
School of  Electrical and  Information Engineering, Guangxi University of Science and Technology，
Guangxi, Liuzhou, 545006
P. R. China
Tel:13633065630
2020年8月12日




At 2020-08-12 10:55:53, "zhanjunpeng" <notifications@github.com> wrote:

get_losses() is a function of MatPower as explained in this link: https://matpower.org/docs/ref/matpower5.0/get_losses.html

Before running the code, the path to the MatPower toolbox needs to be added. The MatPower can be downloaded from github.com/MATPOWER/matpower
